# Generated by Django 5.1.3 on 2025-01-12 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Known_mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_text', models.CharField(max_length=20)),
                ('mac_inf_text', models.CharField(max_length=100)),
                ('device_text', models.CharField(max_length=100)),
                ('count_int', models.IntegerField(default=0)),
                ('first_seen_date', models.DateTimeField(verbose_name='first seen')),
                ('last_seen_date', models.DateTimeField(verbose_name='last seen')),
            ],
        ),
        migrations.CreateModel(
            name='Macinfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_mac_text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_text', models.CharField(max_length=50)),
                ('user_text', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_text', models.CharField(max_length=20)),
                ('oid_text', models.CharField(max_length=150)),
                ('community_text', models.CharField(max_length=50)),
                ('interval_int', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Status_msg',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pushover_text', models.CharField(max_length=256)),
                ('maclookup_text', models.CharField(max_length=256)),
                ('snmp_text', models.CharField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Unknown_mac',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mac_text', models.CharField(max_length=20)),
                ('mac_inf_text', models.CharField(max_length=100)),
                ('device_text', models.CharField(max_length=100)),
                ('first_seen_date', models.DateTimeField(verbose_name='first seen')),
                ('last_seen_date', models.DateTimeField(verbose_name='last seen')),
            ],
        ),
    ]
