# Generated by Django 5.1.3 on 2024-12-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('monithor', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='known_mac',
            old_name='count',
            new_name='count_int',
        ),
        migrations.RenameField(
            model_name='known_mac',
            old_name='device',
            new_name='device_text',
        ),
        migrations.RenameField(
            model_name='known_mac',
            old_name='mac_info',
            new_name='mac_inf_text',
        ),
        migrations.RenameField(
            model_name='unknown_mac',
            old_name='device',
            new_name='device_text',
        ),
        migrations.RenameField(
            model_name='unknown_mac',
            old_name='mac_info',
            new_name='mac_inf_text',
        ),
    ]
