# Generated by Django 4.2.17 on 2025-01-18 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monithor', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='send_bool',
            field=models.BooleanField(default=False),
        ),
    ]
