# Generated by Django 5.1.3 on 2025-01-06 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('monithor', '0003_macinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='source',
            name='interval_int',
            field=models.IntegerField(default=0),
        ),
    ]
